version: '3'
services:
  backend:
    container_name: crud-js-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"

  frontend:
    container_name: crud-js-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"